export const mealDefaultState = {
    mealName: '',
    mealCalories: 0.0, // Unit : Cal
    date: '',
    savedMeals: [],
};

export const FETCH_MEAL_PENDING = 'MEAL/FETCH_MEAL_PENDING';
export const FETCH_MEAL_FULFILLED = 'MEAL/FETCH_MEAL_FULFILLED';
export const FETCH_MEAL_REJECTED = 'MEAL/FETCH_MEAL_REJECTED';

export const SAVE_MEAL_PENDING = 'MEAL/SAVE_MEAL_PENDING';
export const SAVE_MEAL_FULFILLED = 'MEAL/SAVE_MEAL_FULFILLED';
export const SAVE_MEAL_REJECTED = 'MEAL/SAVE_MEAL_REJECTED';

export const UPDATE_MEAL_PENDING = 'MEAL/UPDATE_MEAL_PENDING';
export const UPDATE_MEAL_FULFILLED = 'MEAL/UPDATE_MEAL_FULFILLED';
export const UPDATE_MEAL_REJECTED = 'MEAL/UPDATE_MEAL_REJECTED';

export const DELETE_MEAL_PENDING = 'MEAL/DELETE_MEAL_PENDING';
export const DELETE_MEAL_FULFILLED = 'MEAL/DELETE_MEAL_FULFILLED';
export const DELETE_MEAL_REJECTED = 'MEAL/DELETE_MEAL_REJECTED';
